<form action="<?php echo $block->getGateUrl(); ?>" method="POST" id="concordpay_payment_form" style="display: none">
    <?php $data = $block->getPostData(); ?>
    <?php if (!empty($data)): ?>
        <?php echo $data ?>
    <?php endif; ?>
</form>
<script type="text/javascript">
  window.addEventListener('DOMContentLoaded', function () {
    document.getElementById('concordpay_payment_form').submit();
  });
</script>
